name: Publish
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup

      - name: Publish package (jsr)
        run: pnpm jsr-publish

      - name: Publish package (npm)
        run: pnpm publish
